#!/usr/bin/env bash
# =============================================================================
# Bring up local development infrastructure for the backend API.
#
#   Postgres (pgvector) + Redis in Docker, schema created, tiers seeded,
#   and a bootstrap organization inserted so registration works immediately.
#
# Idempotent: safe to re-run. Nothing is destroyed unless you pass --wipe.
#
# Usage:
#   ./setup_infra.sh            # start infra, create schema, seed
#   ./setup_infra.sh --wipe     # destroy data volumes first, then rebuild
#   ./setup_infra.sh --status   # show what is running and what is in the DB
#
# Afterwards: ./start_backend.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.infra.yml"
ENV_FILE="$SCRIPT_DIR/.env.local"
PROJECT="b2blocal"

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BLUE=$'\033[0;34m'; NC=$'\033[0m'
info()  { echo "${BLUE}[INFO]${NC} $*"; }
ok()    { echo "${GREEN}[OK]${NC} $*"; }
warn()  { echo "${YELLOW}[WARN]${NC} $*"; }
die()   { echo "${RED}[ERROR]${NC} $*" >&2; exit 1; }

WIPE=false
STATUS_ONLY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --wipe)   WIPE=true; shift ;;
        --status) STATUS_ONLY=true; shift ;;
        -h|--help) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) die "Unknown option: $1" ;;
    esac
done

command -v docker >/dev/null || die "docker not found"
docker info >/dev/null 2>&1 || die "Docker daemon not reachable. Start Docker Desktop (or Colima) first."
command -v uv >/dev/null || die "uv not found (https://docs.astral.sh/uv/)"

# ---------------------------------------------------------------- env file ---
# Generated once with real random values. Gitignored. Both this script and
# start_backend.sh read it, so the API and the database agree on credentials.
if [[ ! -f "$ENV_FILE" ]]; then
    info "Generating $ENV_FILE (first run)"
    gen() { python3 -c "import secrets; print(secrets.token_hex(32))"; }
    cat > "$ENV_FILE" <<EOF
# Generated by setup_infra.sh — local development only, never commit.
DATABASE_USER=postgres
DATABASE_NAME=doc_intelligence
POSTGRES_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")
POSTGRES_HOST_PORT=15432
REDIS_HOST_PORT=16379

# JWT secrets must be >= 32 chars or app/core/config.py rejects them at startup.
JWT_SECRET_KEY=$(gen)
REFRESH_SECRET_KEY=$(gen)

# Bootstrap organization — registration requires an existing organization_id,
# so one is created for you. See README.md.
BOOTSTRAP_ORG_ID=$(python3 -c "import uuid; print(uuid.uuid4())")
BOOTSTRAP_ORG_NAME="Local Dev Org"
EOF
    chmod 600 "$ENV_FILE"
    ok "Created $ENV_FILE with generated secrets"
else
    info "Using existing $ENV_FILE"
fi

set -a; source "$ENV_FILE"; set +a
export POSTGRES_PASSWORD DATABASE_USER DATABASE_NAME POSTGRES_HOST_PORT REDIS_HOST_PORT

dc() { docker compose -f "$COMPOSE_FILE" --project-name "$PROJECT" "$@"; }

PSQL_URL="postgresql+asyncpg://${DATABASE_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_HOST_PORT}/${DATABASE_NAME}"

# ------------------------------------------------------------------ status ---
if [[ "$STATUS_ONLY" == true ]]; then
    echo; info "Containers:"
    dc ps --format 'table {{.Service}}\t{{.Status}}\t{{.Ports}}' || true
    echo; info "Database:"
    if dc exec -T postgres pg_isready -U "$DATABASE_USER" -d "$DATABASE_NAME" >/dev/null 2>&1; then
        dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" -tAc \
          "SELECT 'tables: '||count(*) FROM information_schema.tables WHERE table_schema='public';"
        dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" -tAc \
          "SELECT 'organizations: '||count(*) FROM organizations;" 2>/dev/null || echo "organizations: (table missing)"
        dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" -tAc \
          "SELECT 'users: '||count(*) FROM users;" 2>/dev/null || true
    else
        warn "Postgres not accepting connections"
    fi
    exit 0
fi

# -------------------------------------------------------------------- wipe ---
if [[ "$WIPE" == true ]]; then
    warn "About to DESTROY all local dev data (containers and volumes)."
    read -r -p "Type 'WIPE' to confirm: " confirm
    [[ "$confirm" == "WIPE" ]] || die "Aborted."
    dc down -v
    ok "Volumes destroyed"
fi

# ------------------------------------------------------------------- start ---
# Guard against the common case of another Postgres already holding the port —
# otherwise the failure surfaces much later as a confusing auth error against
# somebody else's database.
if lsof -nP -iTCP:"$POSTGRES_HOST_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    if ! docker ps --filter "name=b2blocal-postgres" --format '{{.Names}}' | grep -q .; then
        die "Port $POSTGRES_HOST_PORT is already in use by something that is not our Postgres.
       Free it, or set POSTGRES_HOST_PORT in $ENV_FILE and re-run."
    fi
fi

info "Starting Postgres and Redis"
dc up -d

info "Waiting for health checks"
for i in $(seq 1 60); do
    pg=$(docker inspect b2blocal-postgres --format '{{.State.Health.Status}}' 2>/dev/null || echo starting)
    rd=$(docker inspect b2blocal-redis    --format '{{.State.Health.Status}}' 2>/dev/null || echo starting)
    [[ "$pg" == healthy && "$rd" == healthy ]] && break
    sleep 2
done
[[ "${pg:-}" == healthy ]] || die "Postgres did not become healthy. Check: docker logs b2blocal-postgres"
[[ "${rd:-}" == healthy ]] || die "Redis did not become healthy. Check: docker logs b2blocal-redis"
ok "Postgres and Redis healthy"

# pgvector only installs via the init script on a *fresh* volume; on a reused
# volume it may be absent, so make sure either way.
dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" \
    -c "CREATE EXTENSION IF NOT EXISTS vector;" >/dev/null
ok "pgvector extension present"

# ------------------------------------------------------------------ schema ---
# The biz2bricks CLI needs BOTH DATABASE_URL and DATABASE_PASSWORD: `db init`
# parses the URL via SQLAlchemy, but `seed tiers` connects with raw asyncpg and
# reads the individual credential fields. Passing only the URL fails with
# "password authentication failed".
CLI_ENV="$(mktemp -t b2blocal-cli-env)"
trap 'rm -f "$CLI_ENV"' EXIT
cat > "$CLI_ENV" <<EOF
USE_CLOUD_SQL_CONNECTOR=false
DATABASE_URL=$PSQL_URL
DATABASE_NAME=$DATABASE_NAME
DATABASE_USER=$DATABASE_USER
DATABASE_PASSWORD=$POSTGRES_PASSWORD
DATABASE_HOST=localhost
DATABASE_PORT=$POSTGRES_HOST_PORT
EOF

info "Creating schema"
(cd "$REPO_ROOT" && uv run biz2bricks db init --env-file "$CLI_ENV") >/dev/null 2>&1 \
    || die "Schema creation failed. Re-run verbosely:
       cd $REPO_ROOT && uv run biz2bricks db init --env-file <env>"
TABLES=$(dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" -tAc \
    "SELECT count(*) FROM information_schema.tables WHERE table_schema='public';" | tr -d '[:space:]')
[[ "$TABLES" -gt 0 ]] || die "Schema creation reported success but no tables exist"
ok "Schema created ($TABLES tables)"

info "Seeding subscription tiers"
(cd "$REPO_ROOT" && uv run biz2bricks seed tiers --env-file "$CLI_ENV") >/dev/null 2>&1 || true
TIERS=$(dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" -tAc \
    "SELECT count(*) FROM subscription_tiers;" 2>/dev/null | tr -d '[:space:]' || echo 0)
[[ "${TIERS:-0}" -gt 0 ]] && ok "Subscription tiers seeded ($TIERS)" || warn "No subscription tiers seeded"

# --------------------------------------------------------- bootstrap org -----
# Registration requires an existing organization_id, and organization creation
# is an authenticated endpoint — a chicken-and-egg on a fresh database. Insert
# one directly so `./start_backend.sh` is immediately usable.
dc exec -T postgres psql -U "$DATABASE_USER" -d "$DATABASE_NAME" -v ON_ERROR_STOP=1 >/dev/null <<SQL
INSERT INTO organizations (id, name, plan_type, settings, is_active, subscription_status, created_at, updated_at)
VALUES ('${BOOTSTRAP_ORG_ID}', '${BOOTSTRAP_ORG_NAME}', 'free', '{}'::jsonb, true, 'active', now(), now())
ON CONFLICT (id) DO NOTHING;
SQL
ok "Bootstrap organization ready"

# ------------------------------------------------------------------- done ----
cat <<EOF

${GREEN}Infrastructure ready.${NC}

  Postgres   127.0.0.1:${POSTGRES_HOST_PORT}   db=${DATABASE_NAME} user=${DATABASE_USER}
  Redis      127.0.0.1:${REDIS_HOST_PORT}
  Org ID     ${BOOTSTRAP_ORG_ID}

Next:
  ./start_backend.sh

psql:
  docker exec -it b2blocal-postgres psql -U ${DATABASE_USER} -d ${DATABASE_NAME}

Stop (data kept):   ./stop_infra.sh
Status:             ./setup_infra.sh --status
EOF
